// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8j55efpmLH_maQGM6c7FfnhdhnHcvgM',
    appId: '1:478751399545:web:29b1f61e9bc04064cafea8',
    messagingSenderId: '478751399545',
    projectId: 'flash-chat-5ac4b',
    authDomain: 'flash-chat-5ac4b.firebaseapp.com',
    storageBucket: 'flash-chat-5ac4b.appspot.com',
    measurementId: 'G-GV2B2TM2T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL71iqOVUwtc0d8n0xUm-pRtPdrzBl7es',
    appId: '1:478751399545:android:2d2b21fef1feef46cafea8',
    messagingSenderId: '478751399545',
    projectId: 'flash-chat-5ac4b',
    storageBucket: 'flash-chat-5ac4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1k_o5nVZRQVJFcW1-hRt3KXnDJ11Z95E',
    appId: '1:478751399545:ios:3b9315e9ad466ae4cafea8',
    messagingSenderId: '478751399545',
    projectId: 'flash-chat-5ac4b',
    storageBucket: 'flash-chat-5ac4b.appspot.com',
    iosBundleId: 'ucaselabs.com.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1k_o5nVZRQVJFcW1-hRt3KXnDJ11Z95E',
    appId: '1:478751399545:ios:3b9315e9ad466ae4cafea8',
    messagingSenderId: '478751399545',
    projectId: 'flash-chat-5ac4b',
    storageBucket: 'flash-chat-5ac4b.appspot.com',
    iosBundleId: 'ucaselabs.com.flashchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc8j55efpmLH_maQGM6c7FfnhdhnHcvgM',
    appId: '1:478751399545:web:6b4712cfd395c6facafea8',
    messagingSenderId: '478751399545',
    projectId: 'flash-chat-5ac4b',
    authDomain: 'flash-chat-5ac4b.firebaseapp.com',
    storageBucket: 'flash-chat-5ac4b.appspot.com',
    measurementId: 'G-3D3HR6E6FH',
  );

}